language: elixir
elixir:
  - 1.1.1
  - 1.2.6
  - 1.3.1
cache:
 - _build
 - deps
sudo: false
before_script:
  - mix local.hex --force
  - mix deps.get
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
